spawn_world: "world"
recheck_time: 5
wait_time: 20
teleport_message: "Wait 20 seconds to be teleported if you're stuck."
post_teleport_message: "You've been teleported back to natural spawn after being stuck in a portal. Travel Carefully!"
