spawn_world: "world"
recheck_time: 5
wait_time: 20
countdown_interval: 5
teleport_message: "&4&lWait 20 seconds to be teleported if you're stuck.&r"
countdown_message: "&4&lWait %0 more seconds to be teleported.&r"
post_teleport_message: "&4&lYou've been teleported back to natural spawn after being stuck in a portal. Travel Carefully!&r"
