spawn_world: "world"
recheck_time: 5
wait_time: 60
countdown_interval: 6
teleport_message: "&c&lWait %0 seconds to be teleported if you're stuck.&r"
countdown_message: "&e&lWait %0 more seconds to be teleported.&r"
post_teleport_message: "&6&lYou've been teleported back to natural spawn after being stuck in a portal. Travel Carefully!&r"
teleport_debug: false
